=head1 XSTOOLs - Utilities for Using XESS FPGA Boards

This was the start of the C++ source code for a new version of XSTOOLs.
As of now, it is <b>DEAD</b> and no longer being worked on (at least by me).
All new development is proceeding on the python version of XSTOOLs.

Here are the main sections of this code:

=over 4

=item * XstoolsLib

contains the C++ files for the library of classes used by the user-visible XSTOOLs utilities.

=item * XstoolsApi

contains C source files for an API that allows access to the XSTOOLs library as a DLL.
There is also a Python interface to the DLL.

=item * XstoolsApiTest

contains a badly written, hacked up test program for the XSTOOLs library.

=back
